pipeline:
  lint-charts:
    image: guangbo/chart-testing:v1.0.3
    commands:
      - git remote add anaxexp-charts https://github.com/anaxexp/charts
      - git fetch anaxexp-charts master
      - chart_test.sh --config test/.testenv --no-install
